### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Vadorequest**
Add i18n changes

### CODE REVIEW

**Comment by owenmead** [comment]
Thanks for the PR. Doesn't really need it's own header though. Just update the `Key Config Changes` section?

**Comment by Vadorequest** [comment]
I think that's better like this because most people will store their i18n
someplace else so it doesn't get duplicated. What do you think?

Le 9 nov. 2016 7:33 PM, "Owen Mead-Robins" <notifications@github.com> a
écrit :

**Comment by owenmead** [comment]
How you store it is fine, but it is still a configuration change compared to the non-time version of Pikaday correct? So it should go under the config changes header no?

**Comment by Vadorequest** [comment]
@owenmead Like this then? :)

**Comment by Vadorequest** [comment]
@owenmead Is there anything else to be changed before merging?

**Pull request merged**
